### ISSUE TITLE
Fix nuspec

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.FuncParser#20]

**Comment by msevestre** [comment]
THis is still not ok. The package is not defined for netstandard. Instead it says net45

![image](https://user-images.githubusercontent.com/1041237/62008039-bed2c800-b122-11e9-8c20-a5464f473a1c.png)

**Comment by msevestre** [comment]
And the libs are not in the right place lol
![image](https://user-images.githubusercontent.com/1041237/62008061-e1fd7780-b122-11e9-9863-24fde87efaea.png)

FuncParserNative.dll should not be under the OSPSuite.funcParser  folder but the OSPSuite.FuncParserNative folder

Or i

**Comment by msevestre** [comment]
Let me try to fix this to see if I can move further with the issue in core
