### ISSUE TITLE
FuncNode possible memory leak 

### ISSUE THREAD

**Issue by onwhenrdy** [Open-Systems-Pharmacology/OSPSuite.FuncParser#25]
When i was preparing the Linux CI patch i took a look at the C++ sources to get an overview about `FuncParserNative`. I am currently patching the sources to apply a couple of c++11 zero-overhead abstractions (mainly concering memory safety). I noticed a potential unintended behaviour in `FunkNode`:

In the following function, the member `_firstOperand` (Pointer) is replaced by the caller pointer without deleting the old pointer:
https://github.com/Open-Systems-Pharmacology/OSPSuite.FuncParser/blob/55945e9e986d9ee16b65f42f6c0b25c4d3261406/src/OSPSuite.FuncParserNative/src/FuncNode.cpp#L93-L98

The member is later deleted in the destructor:
https://github.com/Open-Systems-Pharmacology/OSPSuite.FuncParser/blob/55945e9e986d9ee16b65f42f6c0b25c4d3261406/src/OSPSuite.FuncParserNative/src/FuncNode.cpp#L48-L52

This behaviour is similar to the other `FuncNode` members. Is this intended behaviour?

**Comment by Yuri05** [comment]
I don't think that's a memory leak. Subnodes are set only once during parsing a formula.
Also we have performed memory leak analysis on Simmodel+FuncParser quite often in the past.
However deleting old subnodes first is for sure not wrong ;)
