### ISSUE TITLE
Add a TryParse method (true, false) that returns true if the formula can be parsed otherwise false

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.FuncParser#43]

**Comment by Yuri05** [comment]
do we need only this? or also something like TryCalc? because a valid formula still can return NaN or +-Inf.

**Comment by msevestre** [comment]
For me I only need to know if I can calculate the formula. If this is valid, then I will return the value fo the formula (NaN if the value is NaN)
